
spring:
  cloud:
    consul:
      discovery:
        hostname: localhost
      config:
        enabled: true
        profileSeparator: '::'
        format: YAML
        prefixes: config
        default-context: application











#spring:
#  datasource:
#    username: root
#    password: 12345678
#    url: jdbc:mysql://localhost:3306/sap_customer_service
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update