
spring:
  application:
    name: SAPGateway
  cloud:
    consul:
      discovery:
        hostname: localhost
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: SimService
          uri: lb://SimService
          predicates:
            - Path=/sim/**
        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path=/customer/**
        - id: SummaryService
          uri: lb://SummaryService
          predicates:
            - Path=/summary/**

server:
  port: 8000